<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_NavigationLink_1</name>
   <tag></tag>
   <elementGuidId>fe7a4b49-7706-4213-9631-80af70b38b98</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//a[@title = '${GlobalVariable.mAttributetitle}' and (text() = '${GlobalVariable.mAttributetext}' or . = '${GlobalVariable.mAttributetext}')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//a[@title = '${GlobalVariable.Attributetitle}' and (text() = '${GlobalVariable.Attributetext}' or . = '${GlobalVariable.Attributetext}')])[last()]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>b2094822-b0cb-441a-b7e0-25bdf618784a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>waves-effect waves-cyan collapsible-header</value>
      <webElementGuid>ebf95e30-0fa3-408c-9b95-93cd693bf942</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>6d6e5741-a7cd-4e09-b014-45a2cc4949fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>${GlobalVariable.mAttributetitle}</value>
      <webElementGuid>8b30a132-53c6-4492-8aa5-9384a3c0338d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>${GlobalVariable.mAttributetext}</value>
      <webElementGuid>a1a5fc02-f2e9-4a2d-b532-8cce345d4a81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;collapsibleMenuContainer&quot;)/li[@class=&quot;bold active&quot;]/div[@class=&quot;collapsible-body&quot;]/ul[@class=&quot;collapsible collapsible-accordion&quot;]/li[@class=&quot;bold&quot;]/a[@class=&quot;waves-effect waves-cyan collapsible-header&quot;]</value>
      <webElementGuid>a4619bbd-e4b5-48e4-bbdf-172ae92446de</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='collapsibleMenuContainer']/li[4]/div/ul/li/a</value>
      <webElementGuid>887facb0-1b13-42a4-a1de-7ac55b49633a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Receivables')])[2]</value>
      <webElementGuid>fcfc6d8c-b315-40c4-9759-60f98323429a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Logout'])[1]/following::a[36]</value>
      <webElementGuid>90aea66c-4e84-4ee8-8241-51b2abdcc07c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='en'])[1]/following::a[43]</value>
      <webElementGuid>2e99d8ae-2ffa-4089-8d1e-1d3cf11c98e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Privacy Policy'])[1]/preceding::a[123]</value>
      <webElementGuid>8c15b3c7-51be-40ea-a869-fba14a6f987e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[41]</value>
      <webElementGuid>4d5b3882-cc32-4fde-9c82-9b0caad001db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/div/ul/li/a</value>
      <webElementGuid>09e63568-c4af-4780-be88-236c8fe37dd3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
