<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Month_Option</name>
   <tag></tag>
   <elementGuidId>295d1205-e82c-4550-9c68-5c70d6fe65a0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//option[(text() = '${GlobalVariable.month}' or . = '${GlobalVariable.month}') and @ref_element = 'Object Repository/Web/Frame/Main Frame']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>61beacd1-6215-4da6-a16f-fcbe054bac1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Mar</value>
      <webElementGuid>ce243783-5bea-4bc5-a318-6f65915164b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>${GlobalVariable.month}</value>
      <webElementGuid>56a4f5bc-cbc3-43a9-b4df-1aaa9a238e2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Web/Frame/Main Frame</value>
      <webElementGuid>6284152f-4d40-406d-9f99-a106dbcbd7a1</webElementGuid>
   </webElementProperties>
</WebElementEntity>
