<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Month_Option</name>
   <tag></tag>
   <elementGuidId>295d1205-e82c-4550-9c68-5c70d6fe65a0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//option[(text() = '${GlobalVariable.SsMonth}' or . = '${GlobalVariable.SsMonth}') and @ref_element = 'Object Repository/Phase_2/Surendran/DatePick/Page_IvyDMS/iframe_Logout_iContent']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>99d2be30-3cdb-42d7-b259-db194e69c31c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Mar</value>
      <webElementGuid>43832dc6-e45d-47c0-90f1-6232fb7d36f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>${GlobalVariable.SsMonth}</value>
      <webElementGuid>8fff313b-a6db-430c-a900-cec698a14892</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Web/Frame/Main Frame</value>
      <webElementGuid>6a47b162-f837-471f-a81c-9db69ff63023</webElementGuid>
   </webElementProperties>
</WebElementEntity>
