<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Year_Option</name>
   <tag></tag>
   <elementGuidId>1d3f9b17-cb0d-4b9e-9085-ab62e680ec67</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//option[(text() = '${GlobalVariable.SsYear}' or . = '${GlobalVariable.SsYear}') and @ref_element = 'Object Repository/Phase_2/Surendran/DatePick/Page_IvyDMS/iframe_Logout_iContent']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>ad378589-02d4-442d-89ef-954624098084</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>2021</value>
      <webElementGuid>83b9ff2b-73b0-4026-9f2a-cee8b5aaf695</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>${GlobalVariable.SsYear}</value>
      <webElementGuid>194c259a-f68e-4c91-a16b-fe1434f43f87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Web/Frame/Main Frame</value>
      <webElementGuid>900202aa-8ca0-402c-8a34-07d4872fa8ed</webElementGuid>
   </webElementProperties>
</WebElementEntity>
