<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Print_image</name>
   <tag></tag>
   <elementGuidId>b14ecaf3-cd78-4db8-8c43-8ab459780ec8</elementGuidId>
   <imagePath>Image/printicon.png</imagePath>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value>Image/printicon.png</value>
      </entry>
   </selectorCollection>
   <selectorMethod>IMAGE</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
</WebElementEntity>
